{% set name = "LbExec" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lbexec-{{ version }}.tar.gz
  sha256: d1f20384ce01695b08f6d4d884548545fcf44fda00b0c7e32af61e4e41c80f05

build:
  entry_points:
    - lbexec = LbExec.__main__:parse_args
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - click >=8.0
    - lbenv
    - pydantic >=2
    - typer >=0.4.1
    - packaging
    - pyyaml >=6.0
    - uproot

test:
  imports:
    - LbExec
  commands:
    - pip check
    - lbexec --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/LbExec
  dev_url: https://gitlab.cern.ch/lhcb-core/LbExec
  summary: Used for configuring and running LHCb Applications
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryuwd
    - chrisburr
