{% set name = "LbExec" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lbexec-{{ version }}.tar.gz
  sha256: ef9cbc8417d7c38586a882d6274142fe14df8b7bacaa73f39b724be4fb974b3f

build:
  entry_points:
    - lbexec = LbExec.__main__:parse_args
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0
    - lbenv
    - pydantic >=2
    - typer >=0.4.1
    - packaging
    - pyyaml >=6.0
    - uproot

test:
  imports:
    - LbExec
  commands:
    - pip check
    - lbexec --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.cern.ch/lhcb-core/LbExec
  dev_url: https://gitlab.cern.ch/lhcb-core/LbExec
  summary: Used for configuring and running LHCb Applications
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryuwd
    - chrisburr
